echo Sync TestReReco...
rsync -r ../CMSSW/src/TestReReco/ TestReReco
echo Sync MakeTree...
rsync -r ../CMSSW/src/MakeTree/ MakeTree
echo Sync EvtGeneration...
rsync -r ../CMSSW/src/EvtGeneration/ EvtGeneration
echo ...done