export LD_LIBRARY_PATH=$ROOTSYS/lib:$PYTHONDIR/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$ROOTSYS/lib:$PYTHONPATH

# Extract directories
WORKING_DIR=`pwd`
CMSSW_DIR=$WORKING_DIR"/tree/CMSSW_4_2_8_patch7/src"
#cd $CMSSW_DIR
#cmsenv
cd $WORKING_DIR

export CMSSW_DIR
export WORKING_DIR